org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod_id=soulbound_dolls
mod_name=Soulbound Dolls
mod_version=0.1.2
mod_group_id=com.yabo.soulbounddolls
mod_authors=yabo
mod_license=MIT
mod_description=Player-bound dolls for NeoForge.

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.18
neo_version_range=[21.1.18,)
loader_version_range=[4,)
